sudo: false
language: python
python:
  - "2.7"
  - "3.4"
install:
  # Compile LAMMPS interface
  - "cd build_lammps ; cp Makefile.gnu Makefile ; make lammps_factories ; make atomistica ; cd .."
  # Compile standalone code
  - "cd build_standalone ; cp Makefile.gnu Makefile ; make factories ; make mdcore ; cd .."
  # Fetch and install ASE
  - "pip install -r requirements.txt"
  # Compile Python interface
  - "cp setup.cfg.travis setup.cfg ; python setup.py install"
script:
  - "cd tests ; python run_tests.py"
addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - python-numpy
