language: python
python:
  - "2.7"
install:
  - "sudo apt-get update"
  - "sudo apt-get install gfortran lapack python-numpy"
  # Fetch and install ASE
  - "curl https://wiki.fysik.dtu.dk/ase-files/python-ase-3.8.1.3440.tar.gz | tar -zvx ; cd python-ase-3.8.1.3440 ; python setup.py install ; cd .."
  - "cp setup.cfg.gnu setup.cfg ; python setup.py install"
script:
  - "cd tests ; python run_tests.py"
