language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install gfortran liblapack-dev python-numpy"
install:
  # Compile LAMMPS interface
  - "cd build_lammps ; cp Makefile.gnu Makefile ; make lammps_factories ; make atomistica ; cd .."
  # Fetch and install ASE
  - "curl https://wiki.fysik.dtu.dk/ase-files/python-ase-3.8.1.3440.tar.gz | tar -zvx ; cd python-ase-3.8.1.3440 ; python setup.py install ; cd .."
  - "cp setup.cfg.travis setup.cfg ; python setup.py install"
script:
  - "cd tests ; python run_tests.py"
