sudo: false
language: python
python:
  - "2.7"
  - "3.4"
install:
  # Compile LAMMPS interface
  - "cd build_lammps ; cp Makefile.gnu Makefile ; make lammps_factories ; make atomistica ; cd .."
  # Compile standalone code
  - "cd build_standalone ; cp Makefile.gnu Makefile ; make factories ; make mdcore ; cd .."
  # Fetch and install ASE
  - "pip install ase==3.13.0"
  # Compile Python interface
  - "cp setup.cfg.travis setup.cfg ; python setup.py install"
script:
  # Fetch MIO database file.
  - "cd .. ; wget http://www.dftb.org/fileadmin/DFTB/public/slako/mio/mio-1-1.tar.xz ; tar -Jxf mio-1-1.tar.xz ; cd -"
  - "cd tests ; MIO='../../mio-1-1' python run_tests.py"
addons:
  apt:
    packages:
    - gfortran
    - libopenblas-dev
    - liblapack-dev
    - python-numpy
