name: Build Wheels

on:
  push:
    branches:
      - master
      - python312-meson-migration
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for setuptools-scm

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-musllinux_* *-manylinux_i686 *-win32"
          # Install system dependencies
          CIBW_BEFORE_ALL_LINUX: "yum install -y lapack-devel || (apt-get update && apt-get install -y gfortran liblapack-dev)"
          CIBW_BEFORE_ALL_MACOS: >
            brew install gcc lapack &&
            GFORTRAN=$(ls $(brew --prefix gcc)/bin/gfortran-* | head -1) &&
            ln -sf $GFORTRAN /usr/local/bin/gfortran &&
            gfortran --version
          # Use the symlinked gfortran
          CIBW_ENVIRONMENT_MACOS: "FC=gfortran"
          # Build dependencies
          CIBW_BUILD_FRONTEND: "build"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: error
