name: Publish

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Installing Python
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y \
            gfortran libopenblas-dev liblapack-dev \
            python3-dev \
            python3-pip \
            python3-venv \
            meson \
            ninja-build
          python3 -m venv ../venv
          source ../venv/bin/activate
          pip install build

      - name: Build source package
        run: |
          source ../venv/bin/activate
          python3 -m build . -s

      - name: Test installation of source package
        run: |
          source ../venv/bin/activate
          pip install dist/*.tar.gz

      - name: Publish package on PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

