name: CI

on:
  push:
    branches:    
      - '*'
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y gfortran libopenblas-dev liblapack-dev python-numpy libopenmpi-dev
        python3 -m pip install setuptools
        python3 -m pip install -r requirements.txt
    
#    - name: Compile LAMMPS interface
#      run: |
#        cd build_lammps
#        cp Makefile.gnu Makefile
#        make lammps_factories
#        make atomistica
  
    - name: Compile Fortran unit tests
      run: |
        cd build_unittests
        cp Makefile.gnu Makefile
        make unittests

    - name: Compile and install Python bindings
      run: |
        python3 -m pip install .
    
    - name: Compile standalone code
      run: |
        cd build_standalone
        cp Makefile.gnu Makefile
        make factories
        make mdcore

    - name: Fetch Slater-Koster databases for tests
      run: |
        curl https://dftb.org/fileadmin/DFTB/public/slako/mio/mio-1-1.tar.xz | tar -JxC ..
        curl https://dftb.org/fileadmin/DFTB/public/slako/3ob/3ob-3-1.tar.xz | tar -JxC ..

    - name: Run Fortran unit tests
      run: |
        cd build_unittests
        ./unittests

    - name: Run Python binding tests
      run: |
        cd tests
        MIO='../../mio-1-1' DFTB3='../../3ob-3-1' python run_tests.py

    - name: Run standalone example
      run: |
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        for i in `ls -1 $GITHUB_WORKSPACE/examples/standalone`; do
          cd $i
          $GITHUB_WORKSPACE/build_standalone/mdcore-*
        done